- name: Add Connection Plugin vmware
  add_host:
    name: my_vmware
    ansible_connection: vmware_tools
    ansible_vmware_host: "{{ vcenter_server }}"
    ansible_vmware_user: "{{ vcenter_user }}"
    ansible_vmware_password: "{{ vcenter_pass }}"
    ansible_vmware_validate_certs: no
    ansible_vmware_guest_path: "{{ vm_folder }}/{{ inventory_hostname }}"
    ansible_vmware_tools_user: root
    ansible_vmware_tools_password: C4mb14m1!

- name: Example command via vmtools
  delegate_to: my_vmware
  command: ls -l 
  register: cmdout

- debug:
    msg: "{{ cmdout }}"
