# - name: Add Connection Plugin vmware
#   add_host:
#     name: my_vmware
#     ansible_connection: vmware_tools
#     ansible_vmware_host: "{{ vcenter_server }}"
#     ansible_vmware_user: "{{ vcenter_user }}"
#     ansible_vmware_password: "{{ vcenter_pass }}"
#     ansible_vmware_validate_certs: no
#     ansible_vmware_guest_path: "{{ folder }}/{{ inventory_hostname }}"
#     ansible_vmware_tools_user: administrator
#     ansible_vmware_tools_password: C4mb14m1!
#     ansible_shell_type: powershell

- name: Example command via vmtools
  win_command: whoami 
  register: cmdout

- debug:
    msg: "{{ cmdout }}"

- name: Configure IE proxy settings to apply to all users
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: ProxySettingsPerUser
    data: 0
    type: dword
    state: present

- name: Remove any explicit proxies that are set
  win_inet_proxy:
    proxy: ''
    bypass: ''

- name: Remove any proxy settings
  win_http_proxy:
    proxy: ''
    bypass: ''
  register: proxyout


- name: "Change the hostname to {{ new_name }}"
  win_hostname:
    name: "{{ new_name }}" 
  register: hostname

- debug:
    msg: "{{ hostname }}"
